name: CI - Docker build & test

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

permissions:
  contents: read
  packages: write

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          load: true
          tags: |
            ghcr.io/${{ toLower(github.repository) }}:latest
            ghcr.io/${{ toLower(github.repository) }}:${{ github.sha }}

      - name: Run smoke test (execute container)
        run: |
          echo "Running container from built image..."
          docker run --rm ghcr.io/${{ toLower(github.repository) }}:${{ github.sha }} | tee output.txt
          # simple check that main.py produced expected marker line
          if ! grep -q "=== Python 環境動作確認 ===" output.txt; then
            echo "Smoke test failed: marker line not found" >&2
            cat output.txt
            exit 1
          fi
          echo "Smoke test passed"
